version: '2'


services:
  log1:
    build:
      context: .
      dockerfile: Dockerfile
    image: briancfajardo/arep-taller6-robin:log1
    container_name: log1
    ports:
      - "46000"
    networks:
      arepnet:
        ipv4_address: 10.5.0.5
  log2:
    build:
      context: .
      dockerfile: Dockerfile
    image: briancfajardo/arep-taller6-robin:log2
    container_name: log2
    ports:
      - "46000"
    networks:
      arepnet:
        ipv4_address: 10.5.0.6
  log3:
    build:
      context: .
      dockerfile: Dockerfile
    image: briancfajardo/arep-taller6-robin:log3
    container_name: log3
    ports:
      - "46000"
    networks:
      arepnet:
        ipv4_address: 10.5.0.7
  robin:
    build:
      context: .
      dockerfile: Dockerfile1
    image: briancfajardo/arep-taller6-robin:robin
    container_name: robin
    ports:
      - "8080:46000"
    networks:
      arepnet:
        ipv4_address: 10.5.0.4
  #db:
  #  image: mongo:3.6.1
  #  container_name: db
  #  volumes:
  #    - mongodb:/data/db
  #    - mongodb_config:/data/configdb
  #  ports:
  #    - "27017:27017"
  #  networks:
  #    arepnet:
  #      ipv4_address: 10.5.0.8
  #  command: mongod

networks:
  arepnet:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
volumes:
  mongodb:
  mongodb_config: